package api

import (
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/gin-gonic/gin"
)

// mediaHandler serves arbitrary local files for display in the chat UI.
// Used by the show_image tool to return screenshots/images generated by agents.
type mediaHandler struct {
	token string // auth token (same as API token)
}

var allowedMediaExts = map[string]string{
	".png":  "image/png",
	".jpg":  "image/jpeg",
	".jpeg": "image/jpeg",
	".gif":  "image/gif",
	".webp": "image/webp",
	".mp4":  "video/mp4",
	".mov":  "video/quicktime",
	".pdf":  "application/pdf",
}

// ServeMedia GET /api/media?path=/tmp/screenshot.png[&token=xxx]
// Accepts auth via Authorization header OR ?token= query param
// (query param needed because <img src=""> cannot send custom headers)
func (h *mediaHandler) ServeMedia(c *gin.Context) {
	// Auth: accept header or query param
	if h.token != "" {
		auth := c.GetHeader("Authorization")
		qToken := c.Query("token")
		if auth != "Bearer "+h.token && qToken != h.token {
			c.JSON(http.StatusUnauthorized, gin.H{"error": "unauthorized"})
			return
		}
	}

	filePath := c.Query("path")
	if filePath == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "path required"})
		return
	}
	filePath = filepath.Clean(filePath)

	ext := strings.ToLower(filepath.Ext(filePath))
	mimeType, ok := allowedMediaExts[ext]
	if !ok {
		c.JSON(http.StatusForbidden, gin.H{"error": "file type not allowed"})
		return
	}

	data, err := os.ReadFile(filePath)
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "file not found"})
		return
	}

	c.Header("Cache-Control", "max-age=3600")
	c.Data(http.StatusOK, mimeType, data)
}
